project:
  type: book
  output-dir: ../docs/en
  
book:
  title: "Python Tutorial"
  subtitle: "From Basics to Advanced Applications"
  author: "Ameyanagi"
  date: today
  language: en
  
  chapters:
    - index.qmd
    - part: "Foundation"
      chapters:
        - book/01-setup.qmd
        - book/02-git-github.qmd
    - part: "Python Basics"
      chapters:
        - book/03-syntax.qmd
        - book/04-data-types.qmd
        - book/05-control-flow.qmd
        - book/06-functions.qmd
        - book/self-review-1.qmd
    - part: "Object-Oriented Programming"
      chapters:
        - book/07-classes.qmd
        - book/08-inheritance.qmd
    - part: "Advanced Topics"
      chapters:
        - book/09-type-hints.qmd
        - book/10-async.qmd
        - book/11-multiprocessing.qmd
    - part: "Applications"
      chapters:
        - book/12-data-science.qmd

format:
  html:
    theme: 
      - cosmo
      - ../custom.scss
    css: ../styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github
    code-fold: false
    code-tools: true
    
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    colorlinks: true