name: Render and Publish Quarto

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync

      - name: Install Quarto extensions
        run: |
          quarto add --no-prompt r-wasm/quarto-live
          quarto add --no-prompt r-wasm/quarto-drop

      - name: Setup output directories and copy shared assets
        run: |
          # Clean and create all necessary directories
          rm -rf docs
          mkdir -p docs/en/book docs/en/slides docs/ja/book docs/ja/slides docs/en/shared docs/ja/shared
          
          # Copy shared assets (accessible from both book/ and slides/ subdirectories)
          if [ -d "en/shared" ]; then
            cp -r en/shared/* docs/en/shared/
            echo "Copied en/shared assets to docs/en/shared/"
          fi
          if [ -d "ja/shared" ]; then
            cp -r ja/shared/* docs/ja/shared/
            echo "Copied ja/shared assets to docs/ja/shared/"
          fi
          # Copy root shared assets to both language directories
          if [ -d "shared" ]; then
            cp -r shared/* docs/en/shared/ 2>/dev/null || true
            cp -r shared/* docs/ja/shared/ 2>/dev/null || true
            echo "Copied root shared assets to both language directories"
          fi
          
          # Verify shared assets are in place
          ls -la docs/en/shared/ || echo "No English shared assets found"
          ls -la docs/ja/shared/ || echo "No Japanese shared assets found"

      - name: Render main landing page
        run: |
          uv run quarto render index.qmd --to html --output-dir docs

      - name: Render English book
        run: |
          cd en && uv run quarto render --to html

      - name: Render English slides (isolated)
        run: |
          cd en/slides
          quarto add --no-prompt r-wasm/quarto-live
          quarto add --no-prompt r-wasm/quarto-drop
          uv run quarto render
          echo "English slides rendered with isolated configuration"
          # Copy rendered slides to docs directory
          cp -r *.html ../../docs/en/slides/ 2>/dev/null || true
          cp -r *_files/ ../../docs/en/slides/ 2>/dev/null || true
          echo "Copied English slides to docs/en/slides/"
          ls -la ../../docs/en/slides/ | head -10

      - name: Render Japanese book
        run: |
          cd ja && uv run quarto render --to html

      - name: Render Japanese slides (isolated)
        run: |
          cd ja/slides
          quarto add --no-prompt r-wasm/quarto-live
          quarto add --no-prompt r-wasm/quarto-drop
          uv run quarto render
          echo "Japanese slides rendered with isolated configuration"
          # Copy rendered slides to docs directory
          cp -r *.html ../../docs/ja/slides/ 2>/dev/null || true
          cp -r *_files/ ../../docs/ja/slides/ 2>/dev/null || true
          echo "Copied Japanese slides to docs/ja/slides/"
          ls -la ../../docs/ja/slides/ | head -10

      - name: Create language redirect pages
        run: |
          # Create redirect pages for /en/ and /ja/ to point to their respective books
          cat > docs/en/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting to English Book...</title>
            <meta http-equiv="refresh" content="0; url=book/">
            <link rel="canonical" href="book/">
          </head>
          <body>
            <p>Redirecting to <a href="book/">English Book</a>...</p>
          </body>
          </html>
          EOF
          
          cat > docs/ja/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>日本語ブックにリダイレクト中...</title>
            <meta http-equiv="refresh" content="0; url=book/">
            <link rel="canonical" href="book/">
          </head>
          <body>
            <p><a href="book/">日本語ブック</a>にリダイレクト中...</p>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4