name: Render and Publish Quarto

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync

      - name: Install Quarto extensions
        run: |
          quarto add --no-prompt r-wasm/quarto-live
          quarto add --no-prompt r-wasm/quarto-drop

      - name: Setup output directories and copy shared assets
        run: |
          # Clean and create all necessary directories
          rm -rf docs
          mkdir -p docs/en/slides docs/ja/slides docs/en/shared docs/ja/shared
          
          # Copy shared assets first (needed during rendering)
          if [ -d "en/shared" ]; then
            cp -r en/shared/* docs/en/shared/
          fi
          if [ -d "ja/shared" ]; then
            cp -r ja/shared/* docs/ja/shared/
          fi
          # Copy root shared assets to both language directories
          if [ -d "shared" ]; then
            cp -r shared/* docs/en/shared/ 2>/dev/null || true
            cp -r shared/* docs/ja/shared/ 2>/dev/null || true
          fi

      - name: Render main landing page
        run: |
          uv run quarto render index.qmd --to html --output-dir docs

      - name: Render English book
        run: |
          cd en && uv run quarto render --to html --output-dir ../docs/en

      - name: Render English slides (isolated)
        run: |
          cd en/slides
          uv run quarto render
          echo "English slides rendered with isolated configuration"

      - name: Render Japanese book
        run: |
          cd ja && uv run quarto render --to html --output-dir ../docs/ja

      - name: Render Japanese slides (isolated)
        run: |
          cd ja/slides
          uv run quarto render
          echo "Japanese slides rendered with isolated configuration"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4